version: 2
executorType: docker
containerInfo:
  - image: php:5.6.14-apache
    env:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY=kjcndjjksddwdwdw
      - DB_CONNECTION=mysql
      - DB_HOST=127.0.0.1
      - DB_PORT=3306
      - DB_DATABASE=db_test
      - DB_PASSWORD=password
      - DB_USERNAME=root
      - CACHE_DRIVER=memcached
      - QUEUE_DRIVER=sync
      - TZ=Europe/Moscow
      - TIMEZONE=Europe/Moscow

    ports:
        - 80:80
  - image: mariadb:5.5
    env:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=db_test
      #MYSQL_ALLOW_EMPTY_PASSWORD=1
stages:
  build:
    workDir: /var/www/html
    steps:
      - type: shell
        name: Install System Packages
        command: apt-get update && apt-get -y -f install imagemagick php5-imagick libjpeg62-turbo-dev libfreetype6-dev git curl libpng12-dev php5-gd php5-cli libc-client-dev libkrb5-dev MariaDB-client php-soap libxml2-dev
      - type: shell
        name: Modify hosts file
        command: echo 127.0.0.1 cci2-yii2-demo.com | tee -a /etc/hosts
      - type: shell
        name: Install PHP Extensions
        command: docker-php-ext-install pdo pdo_mysql zip mbstring soap
      - type: shell
        name: Configure PHP Imap extension
        command: docker-php-ext-configure imap --with-kerberos --with-imap-ssl \
      - type: shell
        name: Configure PHP GD extension
        command: docker-php-ext-configure gd --with-freetype-dir=/usr/include/freetype2 --with-jpeg-dir=/usr/include/ \
      - type: shell
        name: Install Imap & gd extensions
        command: docker-php-ext-install imap gd
      - type: checkout
      - type: shell
        name: Install Composer
        command: |
         curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
      - type: shell
        name: Install composer asset plugin
        command: composer global require "fxp/composer-asset-plugin:^1.2.0"
      - type: shell
        name: Install Project Dependencies
        command: composer install
      - type: shell
        name: phpinfo
        command: php -i
      - type: shell
        shell: /bin/bash --login #recommend running bash in login shell mode
        name: Modify apache config
        command: |
          a2enmod rewrite
          sed -i "s/\/var\/www\/html/\/var\/www\/html\/web/g" /etc/apache2/sites-available/000-default.conf
          cp cci2-yii2-demo.com.conf /etc/apache2/sites-available/cci2-yii2-demo.com.conf
          a2ensite cci2-yii2-demo.com.conf
          cat /etc/apache2/sites-available/000-default.conf
          cat /etc/apache2/sites-available/cci2-yii2-demo.com.conf

      - type: shell
        shell: /bin/bash --login #recommend running bash in login shell mode
        name: start Apache webserver
        command: |
          service apache2 start
      - type: shell
        shell: /bin/bash --login #recommend running bash in login shell mode
        name: availiable hosts
        command: |
          apache2ctl -S
      - type: shell
        name: checks2
        shell: /bin/bash --login #recommend running bash in login shell mode
        command: |
          curl -v http://localhost:80/index.html
          curl -v http://127.0.0.1:80/index.html
          curl -v http://cci2-yii2-demo.com/index.html
      - type: shell
        name: apache logs
        shell: /bin/bash --login #recommend running bash in login shell mode
        command: |
          ls -la /var/log/apache2/
          tail /var/log/apache2/error.log
          tail /var/log/apache2/cci2-yii2-demo-access.log
          tail /var/log/apache2/cci2-yii2-demo-error.log
          #mysql --password=$DB_PASSWORD --user=$DB_USERNAME --database=$DB_DATABASE --host=$DB_HOST
        # unit
      #- type: shell
      #  name: Run migrations
      #  command: ./tests/bin/yii migrate/up --interactive=0
      - type: shell
        name: Run tests
        command: vendor/bin/codecept run --debug --env circleci